#version: '3.9'

services:
  web:
    image: us-east1-docker.pkg.dev/blog-flask-oneit/blog-repo/flask-blog:latest
    container_name: flask_blog
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/blogdb
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    volumes:
      - blog_data:/var/lib/postgresql/data

volumes:
  blog_data:

